# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'surfaceS\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 780)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Switzerland))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 600))
        self.toolBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 500, 655))
        self.page.setObjectName("page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.timeSlider = QtWidgets.QSlider(self.page)
        self.timeSlider.setMaximum(999)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeSlider)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.timeEdit = QtWidgets.QLineEdit(self.page)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.maxZLineEdit = QtWidgets.QLineEdit(self.page)
        self.maxZLineEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.maxZLineEdit.setObjectName("maxZLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxZLineEdit)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.minZLineEdit = QtWidgets.QLineEdit(self.page)
        self.minZLineEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.minZLineEdit.setObjectName("minZLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.minZLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.pathFigureLineEdit = QtWidgets.QLineEdit(self.page)
        self.pathFigureLineEdit.setObjectName("pathFigureLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pathFigureLineEdit)
        self.saveFigPathLineEdit = QtWidgets.QLabel(self.page)
        self.saveFigPathLineEdit.setObjectName("saveFigPathLineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.saveFigPathLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.saveFigureButton = QtWidgets.QPushButton(self.page)
        self.saveFigureButton.setObjectName("saveFigureButton")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.saveFigureButton)
        self.saveAnimationButton = QtWidgets.QPushButton(self.page)
        self.saveAnimationButton.setObjectName("saveAnimationButton")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.saveAnimationButton)
        self.toolBox.addItem(self.page, "")
        self.experimentParameters = QtWidgets.QWidget()
        self.experimentParameters.setGeometry(QtCore.QRect(0, 0, 500, 655))
        self.experimentParameters.setObjectName("experimentParameters")
        self.label_5 = QtWidgets.QLabel(self.experimentParameters)
        self.label_5.setGeometry(QtCore.QRect(9, 27, 87, 16))
        self.label_5.setObjectName("label_5")
        self.startMachineCoordinatesEdit = QtWidgets.QLineEdit(self.experimentParameters)
        self.startMachineCoordinatesEdit.setGeometry(QtCore.QRect(187, 27, 301, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startMachineCoordinatesEdit.sizePolicy().hasHeightForWidth())
        self.startMachineCoordinatesEdit.setSizePolicy(sizePolicy)
        self.startMachineCoordinatesEdit.setObjectName("startMachineCoordinatesEdit")
        self.setStartCoordinatesButton = QtWidgets.QPushButton(self.experimentParameters)
        self.setStartCoordinatesButton.setGeometry(QtCore.QRect(187, 53, 301, 23))
        self.setStartCoordinatesButton.setObjectName("setStartCoordinatesButton")
        self.jsonFormatParameters = QtWidgets.QPlainTextEdit(self.experimentParameters)
        self.jsonFormatParameters.setGeometry(QtCore.QRect(9, 82, 481, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.jsonFormatParameters.sizePolicy().hasHeightForWidth())
        self.jsonFormatParameters.setSizePolicy(sizePolicy)
        self.jsonFormatParameters.setMinimumSize(QtCore.QSize(0, 300))
        self.jsonFormatParameters.setObjectName("jsonFormatParameters")
        self.startMeasuringButton = QtWidgets.QCommandLinkButton(self.experimentParameters)
        self.startMeasuringButton.setGeometry(QtCore.QRect(9, 605, 172, 41))
        self.startMeasuringButton.setObjectName("startMeasuringButton")
        self.startAcquiringButton = QtWidgets.QCommandLinkButton(self.experimentParameters)
        self.startAcquiringButton.setGeometry(QtCore.QRect(320, 600, 172, 41))
        self.startAcquiringButton.setObjectName("startAcquiringButton")
        self.toolBox.addItem(self.experimentParameters, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout_2.addLayout(self.plotLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.oscilloGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.oscilloGroupBox.setObjectName("oscilloGroupBox")
        self.OscilloscopeGrid = QtWidgets.QGridLayout(self.oscilloGroupBox)
        self.OscilloscopeGrid.setObjectName("OscilloscopeGrid")
        self.connectOscilloscopeButton = QtWidgets.QPushButton(self.oscilloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectOscilloscopeButton.sizePolicy().hasHeightForWidth())
        self.connectOscilloscopeButton.setSizePolicy(sizePolicy)
        self.connectOscilloscopeButton.setObjectName("connectOscilloscopeButton")
        self.OscilloscopeGrid.addWidget(self.connectOscilloscopeButton, 0, 1, 1, 1)
        self.oscilloscopeIPEdit = QtWidgets.QLineEdit(self.oscilloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oscilloscopeIPEdit.sizePolicy().hasHeightForWidth())
        self.oscilloscopeIPEdit.setSizePolicy(sizePolicy)
        self.oscilloscopeIPEdit.setReadOnly(True)
        self.oscilloscopeIPEdit.setObjectName("oscilloscopeIPEdit")
        self.OscilloscopeGrid.addWidget(self.oscilloscopeIPEdit, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.oscilloGroupBox)
        self.signalGeneratorGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.signalGeneratorGroupBox.sizePolicy().hasHeightForWidth())
        self.signalGeneratorGroupBox.setSizePolicy(sizePolicy)
        self.signalGeneratorGroupBox.setMinimumSize(QtCore.QSize(200, 200))
        self.signalGeneratorGroupBox.setObjectName("signalGeneratorGroupBox")
        self.signalGeneratorLayout = QtWidgets.QVBoxLayout(self.signalGeneratorGroupBox)
        self.signalGeneratorLayout.setObjectName("signalGeneratorLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sgConnectButton = QtWidgets.QPushButton(self.signalGeneratorGroupBox)
        self.sgConnectButton.setObjectName("sgConnectButton")
        self.gridLayout_2.addWidget(self.sgConnectButton, 1, 1, 1, 1)
        self.sgARBSelector = QtWidgets.QSpinBox(self.signalGeneratorGroupBox)
        self.sgARBSelector.setReadOnly(False)
        self.sgARBSelector.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sgARBSelector.setMinimum(1)
        self.sgARBSelector.setMaximum(3)
        self.sgARBSelector.setObjectName("sgARBSelector")
        self.gridLayout_2.addWidget(self.sgARBSelector, 3, 0, 1, 1)
        self.sgSendButton = QtWidgets.QPushButton(self.signalGeneratorGroupBox)
        self.sgSendButton.setObjectName("sgSendButton")
        self.gridLayout_2.addWidget(self.sgSendButton, 3, 1, 1, 1)
        self.sgFilePathEdit = QtWidgets.QLineEdit(self.signalGeneratorGroupBox)
        self.sgFilePathEdit.setReadOnly(True)
        self.sgFilePathEdit.setObjectName("sgFilePathEdit")
        self.gridLayout_2.addWidget(self.sgFilePathEdit, 2, 0, 1, 1)
        self.sgChooseFileButton = QtWidgets.QPushButton(self.signalGeneratorGroupBox)
        self.sgChooseFileButton.setObjectName("sgChooseFileButton")
        self.gridLayout_2.addWidget(self.sgChooseFileButton, 2, 1, 1, 1)
        self.sgSerialPortEdit = QtWidgets.QLineEdit(self.signalGeneratorGroupBox)
        self.sgSerialPortEdit.setReadOnly(True)
        self.sgSerialPortEdit.setObjectName("sgSerialPortEdit")
        self.gridLayout_2.addWidget(self.sgSerialPortEdit, 1, 0, 1, 1)
        self.signalGeneratorLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.signalGeneratorGroupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.positiveZButton = QtWidgets.QPushButton(self.groupBox_2)
        self.positiveZButton.setObjectName("positiveZButton")
        self.gridLayout_4.addWidget(self.positiveZButton, 0, 2, 1, 1)
        self.positiveXButton = QtWidgets.QPushButton(self.groupBox_2)
        self.positiveXButton.setObjectName("positiveXButton")
        self.gridLayout_4.addWidget(self.positiveXButton, 1, 2, 1, 1)
        self.negativeZButton = QtWidgets.QPushButton(self.groupBox_2)
        self.negativeZButton.setObjectName("negativeZButton")
        self.gridLayout_4.addWidget(self.negativeZButton, 2, 2, 1, 1)
        self.negativeXButton = QtWidgets.QPushButton(self.groupBox_2)
        self.negativeXButton.setObjectName("negativeXButton")
        self.gridLayout_4.addWidget(self.negativeXButton, 1, 0, 1, 1)
        self.positiveYButton = QtWidgets.QPushButton(self.groupBox_2)
        self.positiveYButton.setObjectName("positiveYButton")
        self.gridLayout_4.addWidget(self.positiveYButton, 0, 1, 1, 1)
        self.negativeYButton = QtWidgets.QPushButton(self.groupBox_2)
        self.negativeYButton.setObjectName("negativeYButton")
        self.gridLayout_4.addWidget(self.negativeYButton, 2, 1, 1, 1)
        self.homeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_4.addWidget(self.homeButton, 0, 0, 1, 1)
        self.unlockButton = QtWidgets.QPushButton(self.groupBox_2)
        self.unlockButton.setObjectName("unlockButton")
        self.gridLayout_4.addWidget(self.unlockButton, 2, 0, 1, 1)
        self.stepEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepEdit.sizePolicy().hasHeightForWidth())
        self.stepEdit.setSizePolicy(sizePolicy)
        self.stepEdit.setObjectName("stepEdit")
        self.gridLayout_4.addWidget(self.stepEdit, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 1, 2, 1)
        self.zeroWorkingCoordinatesButton = QtWidgets.QPushButton(self.groupBox_2)
        self.zeroWorkingCoordinatesButton.setObjectName("zeroWorkingCoordinatesButton")
        self.gridLayout.addWidget(self.zeroWorkingCoordinatesButton, 4, 0, 1, 1)
        self.machineCoordinatesEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.machineCoordinatesEdit.setReadOnly(True)
        self.machineCoordinatesEdit.setObjectName("machineCoordinatesEdit")
        self.gridLayout.addWidget(self.machineCoordinatesEdit, 1, 1, 1, 1)
        self.portCNCEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.portCNCEdit.setObjectName("portCNCEdit")
        self.gridLayout.addWidget(self.portCNCEdit, 0, 0, 1, 1)
        self.connectCNCButton = QtWidgets.QPushButton(self.groupBox_2)
        self.connectCNCButton.setObjectName("connectCNCButton")
        self.gridLayout.addWidget(self.connectCNCButton, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.goToWorkingZeroButton = QtWidgets.QPushButton(self.groupBox_2)
        self.goToWorkingZeroButton.setObjectName("goToWorkingZeroButton")
        self.gridLayout.addWidget(self.goToWorkingZeroButton, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 21))
        self.menubar.setObjectName("menubar")
        self.menusurfaceS = QtWidgets.QMenu(self.menubar)
        self.menusurfaceS.setObjectName("menusurfaceS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenDataFile = QtWidgets.QAction(MainWindow)
        self.actionOpenDataFile.setObjectName("actionOpenDataFile")
        self.actionSaveExperimentFile = QtWidgets.QAction(MainWindow)
        self.actionSaveExperimentFile.setObjectName("actionSaveExperimentFile")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpenExperimentFile = QtWidgets.QAction(MainWindow)
        self.actionOpenExperimentFile.setObjectName("actionOpenExperimentFile")
        self.menusurfaceS.addAction(self.actionOpenDataFile)
        self.menusurfaceS.addAction(self.actionOpenExperimentFile)
        self.menusurfaceS.addAction(self.actionSaveExperimentFile)
        self.menubar.addAction(self.menusurfaceS.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "surfaceS"))
        self.label_2.setText(_translate("MainWindow", "Time :"))
        self.label_3.setText(_translate("MainWindow", "Max Z:"))
        self.maxZLineEdit.setText(_translate("MainWindow", "50"))
        self.label_4.setText(_translate("MainWindow", "Min Z:"))
        self.minZLineEdit.setText(_translate("MainWindow", "-50"))
        self.pathFigureLineEdit.setText(_translate("MainWindow", "figure.eps"))
        self.saveFigPathLineEdit.setText(_translate("MainWindow", "Path of the figure:"))
        self.saveFigureButton.setText(_translate("MainWindow", "Save"))
        self.saveAnimationButton.setText(_translate("MainWindow", "Save animation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Plot toolbox"))
        self.label_5.setText(_translate("MainWindow", "Start coordinates:"))
        self.setStartCoordinatesButton.setText(_translate("MainWindow", "Set start coordinates"))
        self.startMeasuringButton.setText(_translate("MainWindow", "Start measuring"))
        self.startAcquiringButton.setText(_translate("MainWindow", "Start Acquisiton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.experimentParameters), _translate("MainWindow", "Measurement toolbox"))
        self.oscilloGroupBox.setTitle(_translate("MainWindow", "Oscilloscope"))
        self.connectOscilloscopeButton.setText(_translate("MainWindow", "Connect"))
        self.signalGeneratorGroupBox.setTitle(_translate("MainWindow", "Signal generator"))
        self.sgConnectButton.setText(_translate("MainWindow", "Connect"))
        self.sgARBSelector.setPrefix(_translate("MainWindow", "ARB "))
        self.sgSendButton.setText(_translate("MainWindow", "Send"))
        self.sgFilePathEdit.setPlaceholderText(_translate("MainWindow", "path"))
        self.sgChooseFileButton.setText(_translate("MainWindow", "Choose..."))
        self.sgSerialPortEdit.setPlaceholderText(_translate("MainWindow", "serial port"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cartesian robot"))
        self.positiveZButton.setText(_translate("MainWindow", "+Z"))
        self.positiveXButton.setText(_translate("MainWindow", "+X"))
        self.negativeZButton.setText(_translate("MainWindow", "-Z"))
        self.negativeXButton.setText(_translate("MainWindow", "-X"))
        self.positiveYButton.setText(_translate("MainWindow", "+Y"))
        self.negativeYButton.setText(_translate("MainWindow", "-Y"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.unlockButton.setText(_translate("MainWindow", "Unlock"))
        self.stepEdit.setText(_translate("MainWindow", "1"))
        self.zeroWorkingCoordinatesButton.setText(_translate("MainWindow", "Zero working\n"
"coordinates"))
        self.portCNCEdit.setPlaceholderText(_translate("MainWindow", "serial port"))
        self.connectCNCButton.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "Coordinates:"))
        self.goToWorkingZeroButton.setText(_translate("MainWindow", "Go to (0;0;0)"))
        self.menusurfaceS.setTitle(_translate("MainWindow", "Files"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenDataFile.setText(_translate("MainWindow", "Open data file..."))
        self.actionSaveExperimentFile.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionOpenExperimentFile.setText(_translate("MainWindow", "Open experiment file..."))

